# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "minitest", ">= 5.25", "< 7"
  gem "rake", "~> 13.2"
  gem "rubocop", "~> 1.91.0", require: false
end
